name: Docker Build and Push

on:
  push:
    branches:
      - "main"

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: issaurabhpandey/god-poc-app:latest, issaurabhpandey/god-poc:${{ github.run_number  }}